# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Network_Ex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Network_Ex
  pod 'YTKNetwork'

end
